version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env.local # Applies inside the conainer only. Run docker-compose --env-file .env.local up 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
